const aliases: Record<string, string> = {
  fsvmainz05: "mainz",
  acmilan: "milan",
  adodenhaag: "denhaag",
  asroma: "roma",
  athbilbao: "athleticbilbao",
  athmadrid: "atleticomadrid",
  bayernmunchen: "bayernmunich",
  betis: "realbetis",
  birminghamcity: "birmingham",
  blackburnrovers: "blackburn",
  boltonwanderers: "bolton",
  borussiadortmund: "dortmund",
  brighton: "brightonandhovealbion",
  bruggekv: "brugge",
  coventrycity: "coventry",
  buyuksehyr: "istanbulbasaksehir",
  cardiffcity: "cardiff",
  celtavigo: "celta",
  charltonathletic: "charlton",
  clubatleticodemadrid: "atleticomadrid",
  deportivodeacoruna: "lacoruna",
  derbycounty: "derby",
  einfrankfurt: "eintrachtfrankfurt",
  forsittard: "fortunasittard",
  goztep: "goztepe",
  heartofmidlothian: "hearts",
  hullcity: "hull",
  internazionalemilano: "inter",
  intermilan: "inter",
  lincolncity: "lincoln",
  mancity: "manchestercity",
  manunited: "manchesterunited",
  mgladbach: "borussiamonchengladbach",
  necnijmegen: "nec",
  nijmegen: "nec",
  norwichcity: "norwich",
  nottmforest: "nottinghamforest",
  olympiakos: "olympiacos",
  parissg: "parissaintgermain",
  prestonnorthend: "preston",
  psv: "psveindhoven",
  queensparkrangers: "qpr",
  realbetisbalompie: "realbetis",
  sociedad: "realsociedad",
  spbraga: "braga",
  splisbon: "sportinglisbon",
  sportingclubedeportugal: "sportinglisbon",
  stgilloise: "unionsaintgilloise",
  stokecity: "stoke",
  standardliege: "standard",
  swanseacity: "swansea",
  tottenham: "tottenhamhotspur",
  vallecano: "rayovallecano",
  levadiakos: "levadeiakos",
  oficrete: "ofi",
  vitoriadeguimaraes: "guimaraes",
  volosnfc: "volos",
  vfbstuttgart: "stuttgart",
  vitoriasc: "guimaraes",
  westbrom: "westbromwichalbion",
  westhamunited: "westham",
  wolves: "wolverhamptonwanderers",
  zultewaregem: "waregem",
  zwolle: "peczwolle",
  academicodeviseu: "academicoviseu",
  aekathens: "aek",
  aldiriyah: "diriyah",
  alustenau: "austrialustenau",
  amedspor: "amed",
  amedsfk: "amed",
  erzurumbb: "erzurumspor",
  rizespor: "caykurrizespor",
  atleticomg: "atleticomineiro",
  atleticotucuman: "atltucuman",
  athleticopr: "athleticoparanaense",
  basaksehir: "istanbulbasaksehir",
  botafogorj: "botafogo",
  centralcordobadesantiagodelestero: "centralcordoba",
  charlotte: "charlottefc",
  clubamerica: "america",
  clubleon: "leon",
  depriestra: "deportivoriestra",
  deportivoalaves: "alaves",
  estorilpraia: "estoril",
  espanol: "espanyol",
  estrellaamadora: "estrela",
  flamengorj: "flamengo",
  gimnasialp: "gimnasialaplata",
  guadalajarachivas: "cdguadalajara",
  indrivadavia: "independienterivadavia",
  iraklis1908: "iraklis",
  lausanne: "lausannesport",
  racingsantander: "santander",
  redstarbelgrade: "crvenazvezda",
  salzburg: "redbullsalzburg",
  skrapid: "rapidvienna",
  tirol: "wsgtirol",
  vasco: "vascodagama",
  aarhus: "agfaarhus",
  atlantaunited: "atlantaunited",
  atlantaunitedfc: "atlantaunited",
  atlantautd: "atlantaunited",
  atleticjunior: "junior",
  atleticojunior: "junior",
  brannbergen: "brann",
  brndby: "brondby",
  estidianteslp: "estudiantesdelaplata",
  estudianteslp: "estudiantesdelaplata",
  estudiantesriocuarto: "estudiantesderiocuarto",
  fccopenhagen: "copenhagen",
  fcmidtjylland: "midtjylland",
  fcnordsjaelland: "nordsjaelland",
  horsens: "achorsens",
  istanbulbasaksehir: "istanbulbasaksehir",
  kasmpasa: "kasimpasa",
  newyorkcity: "newyorkcityfc",
  newyorkredbulls: "redbullnewyork",
  nordsjlland: "nordsjaelland",
  odense: "odensebk",
  silkeborg: "silkeborgif",
  snderjyske: "sonderjyske",
  svjoskoried: "ried",
  sinttruidense: "sttruiden",
  universitatacraiova: "universitateacraiova",
  unionsantafe: "uniondesantafe",
  lagalaxy: "losangelesgalaxy",
  lafc: "losangeles",
  universitariodeportes: "universitario",
  youngboysbern: "youngboys",
  bodglimt: "bodoglimt",
  lilleosc: "lille",
  internazionale: "inter",
  atleticodemadrid: "atleticomadrid",
  sportingcp: "sportinglisbon",
  como1907: "como",
  slaviapraha: "slaviaprague",
  racingclubdelens: "lens",
  redbullbragantino: "bragantino",
  guadalajara: "cdguadalajara",
  belgranocordoba: "belgrano",
  centralcordobasantiagodelestero: "centralcordoba",
  wsgswarovskitirol: "wsgtirol",
  wolfsberger: "wolfsbergerac",
  lasklinz: "lask",
  rbsalzburg: "redbullsalzburg",
  agf: "agfaarhus",
  odenseboldklub: "odensebk",
  lyngbyboldklub: "lyngby",
  fckbenhavn: "copenhagen",
  // Each of these was proved by the fixtures: the two names met the same
  // opponent at the same kickoff, from different providers, more than once.
  athleticclub: "athleticbilbao",
  staderennais: "rennes",
  deportivo: "lacoruna",
  // Same match, same minute, different wording on both sides — so the fixture
  // evidence, which needs one side to agree, could never pair these.
  svelversberg: "elversberg",
  bayerleverkusen: "leverkusen",
  tsghoffenheim: "hoffenheim",
  // football-data.org spells these out in full, so they never matched the
  // plain spelling every other source uses and each ended up a second club row
  // with its own copy of the fixture. Its fixture sync is gone, but the rows it
  // already wrote still need to resolve to one club.
  az: "azalkmaar",
  atalantabc: "atalanta",
  bayer04leverkusen: "leverkusen",
  bologna1909: "bologna",
  hamburgersv: "hamburgsv",
  sslazio: "lazio",
  tsg1899hoffenheim: "hoffenheim",
  cologne: "koln",
  // A club beside a leftover catalogue entry naming the same club. Each was
  // checked one at a time: name nesting alone is not evidence, since inside a
  // single competition it also pairs Atlético Junior with Boca Juniors and
  // Paris FC with Paris Saint-Germain.
  rheindorfaltach: "altach",
  tsvhartberg: "hartberg",
  rapidvienna: "rapid",
  viborgff: "viborg",
  nkcelje: "celje",
  mjallbyaif: "mjallby",
  omonianicosia: "omonia",
  hapoelbeersheva: "hapoelbeer",
  jagielloniabialystok: "jagiellonia",
  neomsportsclub: "neom",
  institutocordoba: "instituto",
  argentinosjrs: "argentinosjuniors",
};

export function normalizeTeamName(value: string) {
  const normalized = value
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    // German clubs are numbered by founding order — "1. FC Köln", "1. FC Union
    // Berlin" — and the digit survived into the key, so those never matched the
    // plain spelling another provider uses. The trailing period is what marks it
    // as an ordinal: "2 de Mayo" has none, and keeps its number.
    .replace(/^\s*\d+\.\s*/, "")
    .replace(/\b(fc|cf|afc|sk|fk|sc|ssc|pae)\b/g, " ")
    .replace(/[^a-z0-9]+/g, "")
    .replace(/^(club|clube)/, "");
  return aliases[normalized] ?? normalized;
}

export function teamNamesMatch(left: string, right: string) {
  return normalizeTeamName(left) === normalizeTeamName(right);
}
