import Link from "next/link";
import { ArrowRightIcon, Repeat2Icon, UserCheckIcon, UsersRoundIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { DistributionAnalytics } from "@/data/distribution";

export function DistributionAnalyticsPanel({ data }: { data: DistributionAnalytics }) {
  const steps = [{label:"Visits",value:data.funnel.visits,icon:UsersRoundIcon},{label:"Joins",value:data.funnel.joins,icon:UserCheckIcon},{label:"First lock",value:data.funnel.activated,icon:ArrowRightIcon},{label:"Returned",value:data.funnel.returned,icon:Repeat2Icon}];
  return <section id="distribution" className="flex flex-col gap-6"><header className="border-b pb-5"><h2 className="font-heading text-4xl font-bold uppercase">Distribution</h2><p className="mt-2 text-muted-foreground">Acquisition, activation, and retention based on real member behavior.</p></header>
    <div className="border"><div className="flex items-center justify-between gap-4 border-b p-5"><h3 className="font-heading text-2xl font-bold uppercase">Visit → Join → Lock → Return</h3><Badge variant="outline">All time</Badge></div><div className="grid sm:grid-cols-2 lg:grid-cols-4">{steps.map(({label,value,icon:Icon},index)=><div key={label} className="relative border-b p-5 sm:border-r lg:border-b-0"><Icon className="size-5 text-primary"/><span className="mt-4 block text-xs font-bold uppercase text-muted-foreground">{label}</span><strong className="mt-1 block font-heading text-4xl">{value===null?"Not tracked":value}</strong>{index<steps.length-1?<ArrowRightIcon className="absolute top-1/2 -right-3 hidden size-5 bg-background text-primary lg:block"/>:null}</div>)}</div>{data.funnel.visits===null?<p className="border-t p-4 text-sm text-muted-foreground">Visitor analytics are not installed yet. Join-to-return metrics are complete; the UI does not invent a visit count.</p>:null}</div>
    <div className="grid gap-6 xl:grid-cols-2"><div className="border"><header className="border-b p-5"><h3 className="font-heading text-2xl font-bold uppercase">Source performance</h3></header>{data.sources.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted text-xs uppercase"><tr><th className="p-3">Source</th><th className="p-3">Joins</th><th className="p-3">First locks</th><th className="p-3">Returns</th><th className="p-3">Activation</th></tr></thead><tbody className="divide-y">{data.sources.map((source)=><tr key={source.source}><th className="p-3 font-semibold">{source.source.replaceAll("_"," ")}</th><td className="p-3">{source.joins}</td><td className="p-3">{source.activated}</td><td className="p-3">{source.returned}</td><td className="p-3 font-bold text-primary">{source.activationRate}%</td></tr>)}</tbody></table></div>:<p className="p-6 text-sm text-muted-foreground">No acquisition sources yet.</p>}</div>
      <div className="border"><header className="border-b p-5"><h3 className="font-heading text-2xl font-bold uppercase">Community activation</h3></header>{data.communities.length?<div className="divide-y">{data.communities.map((community)=><article key={community.slug} className="grid grid-cols-[1fr_auto] gap-3 p-4"><div><Link href={`/teams/${community.slug}`} className="font-bold hover:text-primary">{community.name}</Link><p className="text-xs text-muted-foreground">{community.members} members · {community.locks} lifetime locks</p></div><Badge variant={community.active?"default":"outline"}>{community.active} active</Badge></article>)}</div>:<p className="p-6 text-sm text-muted-foreground">Club communities appear after members choose who they represent.</p>}</div></div>
  </section>;
}
