import Link from "next/link";
import { CalendarDaysIcon, ShieldAlertIcon, UsersRoundIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { AdminManagementSummary } from "@/services/admin-diagnostics";

const formatter = new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC", timeZoneName: "short" });

export function AdminManagementPanels({ data }: { data: AdminManagementSummary }) {
  const counts = [["Accounts", data.counts.users], ["Enabled leagues", data.counts.enabledLeagues], ["Upcoming fixtures", data.counts.upcomingFixtures], ["Provisional records", data.counts.provisionalRecords]];
  return <section className="flex flex-col gap-5" aria-labelledby="management-heading"><div><h2 id="management-heading" className="font-heading text-3xl font-bold uppercase">Product management</h2><p className="mt-2 text-muted-foreground">Read-first operational views for the entities that shape the live product.</p></div><dl className="grid gap-px border bg-border sm:grid-cols-2 xl:grid-cols-4">{counts.map(([label,value]) => <div key={label} className="bg-background p-5"><dt className="text-xs font-bold uppercase text-muted-foreground">{label}</dt><dd className="mt-2 font-heading text-3xl font-bold">{value}</dd></div>)}</dl><div className="grid gap-5 xl:grid-cols-2"><Card className="rounded-none"><CardHeader><CardTitle className="flex items-center gap-2 font-heading text-2xl font-bold uppercase"><CalendarDaysIcon className="size-5" />Upcoming fixtures</CardTitle><CardDescription>Next scheduled inventory across enabled competition feeds.</CardDescription></CardHeader><CardContent className="p-0">{data.upcoming.length ? <ul className="divide-y border-t">{data.upcoming.map((item) => <li key={item.id} className="p-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{item.league}</Badge><strong>{item.fixture}</strong></div><p className="mt-1 text-sm text-muted-foreground">{item.matchweek} · {formatter.format(new Date(item.kickoffAt))}</p></li>)}</ul> : <p className="border-t p-6 text-muted-foreground">No upcoming fixtures are loaded.</p>}</CardContent></Card><Card className="rounded-none"><CardHeader><CardTitle className="flex items-center gap-2 font-heading text-2xl font-bold uppercase"><UsersRoundIcon className="size-5" />Recent accounts</CardTitle><CardDescription>Participation at a glance. Open a public profile to inspect its permanent record.</CardDescription></CardHeader><CardContent className="p-0">{data.accounts.length ? <ul className="divide-y border-t">{data.accounts.map((account) => <li key={account.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><Link href={`/specialists/${account.id}`} className="font-bold hover:text-primary">{account.name}</Link><p className="truncate text-sm text-muted-foreground">{account.email}</p></div><div className="flex gap-2"><Badge variant="secondary">{account.independentPicks} picks</Badge><Badge variant="outline">{account.follows} follows</Badge></div></li>)}</ul> : <p className="border-t p-6 text-muted-foreground">No accounts yet.</p>}</CardContent></Card></div>{data.counts.provisionalRecords ? <div className="flex items-start gap-3 border border-primary p-4"><ShieldAlertIcon className="mt-0.5 size-5 shrink-0 text-primary" /><div><strong>Founding-season review</strong><p className="mt-1 text-sm text-muted-foreground">{data.counts.provisionalRecords} league records are building evidence below the 10-lock public ranking threshold. They remain visible as provisional and cannot be followed.</p></div></div> : null}</section>;
}
