export type CatalogRegion = "Europe" | "Americas" | "Asia" | "Africa" | "Oceania";

export type CatalogEntry = {
  externalId: string; country: string; countryCode: string; flagUrl: string | null;
  name: string; slug: string; shortName: string; region: CatalogRegion; priority: number;
  providerSeason: string; seasonName: string; startDate: string; endDate: string; logoUrl: string | null;
};

export const catalogEntries: CatalogEntry[] = [
  {"externalId":"39","country":"England","countryCode":"GB","flagUrl":"https://media.api-sports.io/flags/gb-eng.svg","name":"Premier League","slug":"premier-league","shortName":"PL","region":"Europe","priority":1,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-21","endDate":"2027-05-30","logoUrl":"https://media.api-sports.io/football/leagues/39.png"},
  {"externalId":"2","country":"Europe","countryCode":"EU","flagUrl":null,"name":"UEFA Champions League","slug":"uefa-champions-league","shortName":"UCL","region":"Europe","priority":2,"providerSeason":"2026","seasonName":"2026","startDate":"2026-07-07","endDate":"2026-09-08","logoUrl":"https://media.api-sports.io/football/leagues/2.png"},
  {"externalId":"140","country":"Spain","countryCode":"ES","flagUrl":"https://media.api-sports.io/flags/es.svg","name":"La Liga","slug":"la-liga","shortName":"LAL","region":"Europe","priority":3,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-15","endDate":"2027-05-30","logoUrl":"https://media.api-sports.io/football/leagues/140.png"},
  {"externalId":"135","country":"Italy","countryCode":"IT","flagUrl":"https://media.api-sports.io/flags/it.svg","name":"Serie A","slug":"serie-a","shortName":"SA","region":"Europe","priority":4,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-22","endDate":"2027-05-30","logoUrl":"https://media.api-sports.io/football/leagues/135.png"},
  {"externalId":"78","country":"Germany","countryCode":"DE","flagUrl":"https://media.api-sports.io/flags/de.svg","name":"Bundesliga","slug":"bundesliga","shortName":"BUN","region":"Europe","priority":5,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-28","endDate":"2027-05-22","logoUrl":"https://media.api-sports.io/football/leagues/78.png"},
  {"externalId":"61","country":"France","countryCode":"FR","flagUrl":"https://media.api-sports.io/flags/fr.svg","name":"Ligue 1","slug":"ligue-1","shortName":"L1","region":"Europe","priority":6,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-21","endDate":"2027-05-29","logoUrl":"https://media.api-sports.io/football/leagues/61.png"},
  {"externalId":"3","country":"Europe","countryCode":"EU","flagUrl":null,"name":"Europa League","slug":"europa-league","shortName":"UEL","region":"Europe","priority":7,"providerSeason":"2026","seasonName":"2026","startDate":"2026-07-09","endDate":"2026-09-16","logoUrl":"https://media.api-sports.io/football/leagues/3.png"},
  {"externalId":"71","country":"Brazil","countryCode":"BR","flagUrl":"https://media.api-sports.io/flags/br.svg","name":"Brasileirão Série A","slug":"brasileirao-serie-a","shortName":"BRA","region":"Americas","priority":8,"providerSeason":"2026","seasonName":"2026","startDate":"2026-01-28","endDate":"2026-12-02","logoUrl":"https://media.api-sports.io/football/leagues/71.png"},
  {"externalId":"203","country":"Türkiye","countryCode":"TR","flagUrl":"https://media.api-sports.io/flags/tr.svg","name":"Süper Lig","slug":"super-lig","shortName":"SÜL","region":"Europe","priority":9,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-14","endDate":"2027-05-23","logoUrl":"https://media.api-sports.io/football/leagues/203.png"},
  {"externalId":"94","country":"Portugal","countryCode":"PT","flagUrl":"https://media.api-sports.io/flags/pt.svg","name":"Liga Portugal","slug":"primeira-liga","shortName":"LP","region":"Europe","priority":10,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-07","endDate":"2027-05-16","logoUrl":"https://media.api-sports.io/football/leagues/94.png"},
  {"externalId":"88","country":"Netherlands","countryCode":"NL","flagUrl":"https://media.api-sports.io/flags/nl.svg","name":"Eredivisie","slug":"eredivisie","shortName":"ERE","region":"Europe","priority":11,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-07","endDate":"2027-05-23","logoUrl":"https://media.api-sports.io/football/leagues/88.png"},
  {"externalId":"40","country":"England","countryCode":"GB","flagUrl":"https://media.api-sports.io/flags/gb-eng.svg","name":"EFL Championship","slug":"efl-championship","shortName":"EFL","region":"Europe","priority":12,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-14","endDate":"2027-05-01","logoUrl":"https://media.api-sports.io/football/leagues/40.png"},
  {"externalId":"262","country":"Mexico","countryCode":"MX","flagUrl":"https://media.api-sports.io/flags/mx.svg","name":"Liga MX","slug":"liga-mx","shortName":"LMX","region":"Americas","priority":13,"providerSeason":"2026","seasonName":"2026","startDate":"2026-07-17","endDate":"2026-11-23","logoUrl":"https://media.api-sports.io/football/leagues/262.png"},
  {"externalId":"253","country":"United States / Canada","countryCode":"US-CA","flagUrl":null,"name":"MLS","slug":"major-league-soccer","shortName":"MLS","region":"Americas","priority":14,"providerSeason":"2026","seasonName":"2026","startDate":"2026-02-21","endDate":"2026-11-08","logoUrl":"https://media.api-sports.io/football/leagues/253.png"},
  {"externalId":"128","country":"Argentina","countryCode":"AR","flagUrl":"https://media.api-sports.io/flags/ar.svg","name":"Argentine Primera División","slug":"liga-profesional-argentina","shortName":"ARG","region":"Americas","priority":15,"providerSeason":"2026","seasonName":"2026","startDate":"2026-01-22","endDate":"2026-11-08","logoUrl":"https://media.api-sports.io/football/leagues/128.png"},
  {"externalId":"307","country":"Saudi Arabia","countryCode":"SA","flagUrl":"https://media.api-sports.io/flags/sa.svg","name":"Saudi Pro League","slug":"saudi-arabia-pro-league","shortName":"SPL","region":"Asia","priority":16,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-13","endDate":"2027-05-28","logoUrl":"https://media.api-sports.io/football/leagues/307.png"},
  {"externalId":"144","country":"Belgium","countryCode":"BE","flagUrl":"https://media.api-sports.io/flags/be.svg","name":"Belgian Pro League","slug":"belgium-jupiler-pro-league","shortName":"BPL","region":"Europe","priority":17,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-07","endDate":"2027-05-22","logoUrl":"https://media.api-sports.io/football/leagues/144.png"},
  {"externalId":"179","country":"Scotland","countryCode":"GB-SCT","flagUrl":"https://media.api-sports.io/flags/gb-sct.svg","name":"Scottish Premiership","slug":"scotland-premiership","shortName":"SCP","region":"Europe","priority":18,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-07-31","endDate":"2027-04-10","logoUrl":"https://media.api-sports.io/football/leagues/179.png"},
  {"externalId":"13","country":"South America","countryCode":"CONMEBOL","flagUrl":null,"name":"Copa Libertadores","slug":"copa-libertadores","shortName":"LIB","region":"Americas","priority":19,"providerSeason":"2026","seasonName":"2026","startDate":"2026-02-04","endDate":"2026-09-15","logoUrl":"https://media.api-sports.io/football/leagues/13.png"},
  {"externalId":"848","country":"Europe","countryCode":"EU","flagUrl":null,"name":"UEFA Conference League","slug":"uefa-conference-league","shortName":"UECL","region":"Europe","priority":20,"providerSeason":"2026","seasonName":"2026","startDate":"2026-07-07","endDate":"2026-10-15","logoUrl":"https://media.api-sports.io/football/leagues/848.png"},
  {"externalId":"197","country":"Greece","countryCode":"GR","flagUrl":"https://media.api-sports.io/flags/gr.svg","name":"Greek Super League","slug":"super-league-greece","shortName":"GSL","region":"Europe","priority":21,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-08-22","endDate":"2027-03-20","logoUrl":"https://media.api-sports.io/football/leagues/197.png"},
  {"externalId":"218","country":"Austria","countryCode":"AT","flagUrl":"https://media.api-sports.io/flags/at.svg","name":"Austrian Bundesliga","slug":"austria-bundesliga","shortName":"ABL","region":"Europe","priority":22,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-07-31","endDate":"2027-02-27","logoUrl":"https://media.api-sports.io/football/leagues/218.png"},
  {"externalId":"207","country":"Switzerland","countryCode":"CH","flagUrl":"https://media.api-sports.io/flags/ch.svg","name":"Swiss Super League","slug":"switzerland-super-league","shortName":"SSL","region":"Europe","priority":23,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-07-25","endDate":"2027-02-06","logoUrl":"https://media.api-sports.io/football/leagues/207.png"},
  {"externalId":"119","country":"Denmark","countryCode":"DK","flagUrl":"https://media.api-sports.io/flags/dk.svg","name":"Danish Superliga","slug":"denmark-superliga","shortName":"DSL","region":"Europe","priority":24,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-07-24","endDate":"2027-03-21","logoUrl":"https://media.api-sports.io/football/leagues/119.png"},
  {"externalId":"345","country":"Czech Republic","countryCode":"CZ","flagUrl":"https://media.api-sports.io/flags/cz.svg","name":"Czech First League","slug":"czech-republic-czech-liga","shortName":"CFL","region":"Europe","priority":25,"providerSeason":"2026","seasonName":"2026–27","startDate":"2026-07-25","endDate":"2027-04-24","logoUrl":"https://media.api-sports.io/football/leagues/345.png"},
];
