"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { CalendarPlusIcon, CheckIcon, CircleAlertIcon, ListFilterIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type Week={id:string;league:string;slug:string;name:string;lockAt:string;startAt:string;endAt:string;status:string;fixtures:number;ownPick:boolean;followedPick:boolean};

export function CalendarPlanner({weeks}:{weeks:Week[]}){
 const[view,setView]=useState<"month"|"week">("month"),[league,setLeague]=useState("all"),[needsAction,setNeedsAction]=useState(false);
 const leagues=[...new Set(weeks.map(x=>x.league))];
 const visible=useMemo(()=>weeks.filter(x=>(league==="all"||x.league===league)&&(!needsAction||(!x.ownPick&&!x.followedPick))),[league,needsAction,weeks]);
 const groups=Map.groupBy(visible,(week)=>view==="month"?new Intl.DateTimeFormat("en",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(week.lockAt)):`Week of ${new Intl.DateTimeFormat("en",{month:"short",day:"numeric",timeZone:"UTC"}).format(startOfWeek(new Date(week.lockAt)))}`);
 function download(){const body=visible.map(w=>[`BEGIN:VEVENT`,`UID:${w.id}@leaguecred`,`DTSTART:${ics(w.lockAt)}`,`DTEND:${ics(w.startAt)}`,`SUMMARY:${escapeIcs(`${w.league}: ${w.name} lock`)}`,`URL:${location.origin}/leagues/${w.slug}`,`END:VEVENT`].join("\r\n")).join("\r\n");const blob=new Blob([`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//LeagueCred//Matchweeks//EN\r\n${body}\r\nEND:VCALENDAR`],{type:"text/calendar"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="leaguecred-matchweeks.ics";a.click();URL.revokeObjectURL(a.href)}
 return <><section className="mt-7 grid gap-3 border-y py-5 lg:grid-cols-[auto_1fr_auto] lg:items-center" aria-label="Calendar controls"><div className="flex gap-2"><Button size="sm" variant={view==="month"?"default":"outline"} aria-pressed={view==="month"} onClick={()=>setView("month")}>Month</Button><Button size="sm" variant={view==="week"?"default":"outline"} aria-pressed={view==="week"} onClick={()=>setView("week")}>Week</Button></div><div className="flex gap-2 overflow-x-auto"><Button size="sm" variant={league==="all"?"secondary":"outline"} onClick={()=>setLeague("all")}>All leagues</Button>{leagues.map(x=><Button key={x} size="sm" variant={league===x?"secondary":"outline"} onClick={()=>setLeague(x)}>{x}</Button>)}</div><div className="flex gap-2"><Button size="sm" variant={needsAction?"default":"outline"} aria-pressed={needsAction} onClick={()=>setNeedsAction(x=>!x)}><ListFilterIcon data-icon="inline-start"/>Needs action</Button><Button size="sm" variant="outline" onClick={download}><CalendarPlusIcon data-icon="inline-start"/>Add to calendar</Button></div></section><div className="mt-8 grid gap-10" aria-live="polite">{[...groups].map(([label,entries])=><section key={label} aria-labelledby={`calendar-${slug(label)}`}><h2 id={`calendar-${slug(label)}`} className="font-heading text-3xl font-bold uppercase">{label}</h2><div className="mt-3 divide-y border-y">{entries.map(week=><article key={week.id} className="grid gap-4 px-4 py-5 md:grid-cols-[150px_1fr_auto] md:items-center"><time dateTime={week.lockAt} className="font-heading text-2xl">{new Intl.DateTimeFormat("en",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"UTC"}).format(new Date(week.lockAt))} UTC</time><div><Link href={`/leagues/${week.slug}`} className="font-bold hover:text-primary">{week.league} · {week.name}</Link><p className="mt-1 text-sm text-muted-foreground">{week.fixtures} fixtures · {week.status}</p></div><div>{week.ownPick?<Badge><CheckIcon data-icon="inline-start"/>Your lock</Badge>:week.followedPick?<Badge variant="outline"><CheckIcon data-icon="inline-start"/>Following</Badge>:<Badge variant="destructive"><CircleAlertIcon data-icon="inline-start"/>Action needed</Badge>}</div></article>)}</div></section>)}{visible.length===0?<div className="border p-10 text-center"><h2 className="font-heading text-3xl font-bold uppercase">Calendar clear</h2><p className="mt-2 text-muted-foreground">No matchweeks match these filters.</p></div>:null}</div></>;
}
function startOfWeek(date:Date){const d=new Date(date);d.setUTCDate(d.getUTCDate()-d.getUTCDay());d.setUTCHours(0,0,0,0);return d}
function ics(value:string){return new Date(value).toISOString().replaceAll("-","").replaceAll(":","").replace(/\.\d{3}Z$/,"Z")}
function escapeIcs(value:string){return value.replaceAll(",","\\,").replaceAll(";","\\;")}
function slug(value:string){return value.toLowerCase().replaceAll(/[^a-z0-9]+/g,"-")}
