"use client";
import { useEffect, useState } from "react";
import { LayoutDashboardIcon, Settings2Icon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Toggle } from "@/components/ui/toggle";
const choices=[['progress','Progress'],['activity','Activity'],['milestones','Milestones'],['recommendations','Recommendations']] as const;
function saved(){if(typeof window==="undefined")return{compact:false,hidden:[] as string[]};try{const p=JSON.parse(localStorage.getItem('leaguecred-dashboard')||'{}');return{compact:Boolean(p.compact),hidden:Array.isArray(p.hidden)?p.hidden:[]}}catch{return{compact:false,hidden:[] as string[]}}}
export function DashboardPreferences(){const initial=useState(saved)[0];const[open,setOpen]=useState(false),[compact,setCompact]=useState(initial.compact),[hidden,setHidden]=useState<string[]>(initial.hidden);useEffect(()=>{document.documentElement.dataset.dashboardDensity=compact?'compact':'comfortable';for(const[id]of choices){const el=document.querySelector(`[data-dashboard-section="${id}"]`) as HTMLElement|null;if(el)el.hidden=hidden.includes(id)}localStorage.setItem('leaguecred-dashboard',JSON.stringify({compact,hidden}))},[compact,hidden]);return <><Button variant="outline" onClick={()=>setOpen(true)}><Settings2Icon data-icon="inline-start"/>Customize dashboard</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="rounded-none sm:max-w-lg"><DialogHeader><LayoutDashboardIcon className="size-7 text-primary"/><DialogTitle className="font-heading text-3xl font-bold uppercase">Dashboard layout</DialogTitle><DialogDescription>Choose the density and sections that help you focus. Preferences stay on this device.</DialogDescription></DialogHeader><div className="grid gap-3"><div className="flex items-center justify-between border p-4"><div><strong>Compact density</strong><p className="text-sm text-muted-foreground">Reduce vertical spacing.</p></div><Toggle pressed={compact} onPressedChange={setCompact} variant="outline">{compact?'On':'Off'}</Toggle></div>{choices.map(([id,label])=><div key={id} className="flex items-center justify-between border p-4"><strong>{label}</strong><Toggle pressed={!hidden.includes(id)} onPressedChange={()=>setHidden(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id])} variant="outline">{hidden.includes(id)?'Hidden':'Shown'}</Toggle></div>)}</div></DialogContent></Dialog></>}
