"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CheckIcon, CopyIcon, CrownIcon, Share2Icon, UserPlusIcon } from "lucide-react";
import { becomeCommunityCaptain } from "@/app/invite/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { toast } from "@/components/ui/toast";
import type { CommunityIdentity, ReferralDashboard } from "@/data/distribution";

const milestones = [1, 3, 5, 10];

export function ReferralCenter({ data, identity, inviteUrl }: { data: ReferralDashboard; identity: CommunityIdentity; inviteUrl: string }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [captainMessage, setCaptainMessage] = useState("");
  const message = `Join me on LeagueCred. Make one selective Daily Lock in the football community you genuinely know. It is completely free: ${inviteUrl}`;
  async function copy(value = inviteUrl) { await navigator.clipboard.writeText(value); toast.add({ title: "Invitation copied", description: "Send it to a supporter who genuinely knows their club.", type: "success" }); }
  async function share() { if (navigator.share) await navigator.share({ title: "Join LeagueCred", text: message, url: inviteUrl }); else await copy(message); }
  function becomeCaptain() { startTransition(async () => { const result = await becomeCommunityCaptain(); setCaptainMessage(result.ok ? `You now captain the ${identity.teamName} community.` : result.message); if (result.ok) router.refresh(); }); }
  return <div className="page-shell py-10 sm:py-16">
    <header className="grid gap-6 border-b pb-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="display-title">Invite supporters.</h1><p className="mt-4 max-w-2xl text-lg text-muted-foreground">Grow a network of people who know different clubs and leagues. Activation counts only when an invited member makes a real Daily Lock.</p></div><div className="border px-5 py-4"><span className="text-xs font-bold uppercase text-muted-foreground">Representing</span><strong className="mt-1 block font-heading text-3xl uppercase">{identity.teamName ?? "Choose your club"}</strong><Badge className="mt-2">{identity.role.replace("_", " ")}</Badge></div></header>
    <section className="mt-8 border" aria-labelledby="invite-link-heading"><div className="border-b p-5"><h2 id="invite-link-heading" className="font-heading text-3xl font-bold uppercase">Your invitation link</h2><p className="mt-1 text-sm text-muted-foreground">Each activated supporter is attributed to you permanently.</p></div><div className="grid gap-3 p-5 sm:grid-cols-[1fr_auto_auto]"><code className="min-w-0 overflow-x-auto border bg-muted px-4 py-3 text-sm">{inviteUrl}</code><Button variant="outline" onClick={() => copy()}><CopyIcon data-icon="inline-start" />Copy</Button><Button onClick={share}><Share2Icon data-icon="inline-start" />Share invite</Button></div></section>
    <section className="mt-6 border" aria-labelledby="progress-heading"><div className="flex items-end justify-between gap-4 border-b p-5"><div><h2 id="progress-heading" className="font-heading text-3xl font-bold uppercase">Activated-member progress</h2><p className="mt-1 text-sm text-muted-foreground">{data.activated} of {Math.max(10, data.activated)} activated</p></div><strong className="font-heading text-5xl text-primary">{data.activated}</strong></div><ol className="grid grid-cols-4 p-5">{milestones.map((milestone) => { const reached = data.activated >= milestone; return <li key={milestone} className="flex flex-col items-center gap-2 text-center"><span className={reached ? "flex size-10 items-center justify-center rounded-full bg-primary font-bold" : "flex size-10 items-center justify-center rounded-full border font-bold"}>{reached ? <CheckIcon className="size-5" /> : milestone}</span><span className="text-xs font-semibold">{reached ? "Achieved" : milestone === 10 ? "Community builder" : "Up next"}</span></li>; })}</ol></section>
    <section className="mt-6 border" aria-labelledby="referred-heading"><div className="flex items-end justify-between gap-4 border-b p-5"><div><h2 id="referred-heading" className="font-heading text-3xl font-bold uppercase">Your referred supporters</h2><p className="mt-1 text-sm text-muted-foreground">Joined is not the finish line. Daily Lock participation is.</p></div><Badge variant="outline">{data.total} total</Badge></div>{data.members.length ? <div className="divide-y">{data.members.map((member) => <article key={member.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><strong>{member.name}</strong><p className="text-xs text-muted-foreground">{member.teamName ? `Representing ${member.teamName}` : "Club not selected yet"}</p></div><span className="text-sm">{member.locks} lock{member.locks === 1 ? "" : "s"}</span><Badge variant={member.activatedAt ? "default" : "outline"}>{member.activatedAt ? "Activated" : "Joined"}</Badge></article>)}</div> : <div className="p-8 text-center"><UserPlusIcon className="mx-auto size-8 text-primary" /><h3 className="mt-3 font-heading text-2xl font-bold uppercase">Your first invitation starts the network</h3><p className="mx-auto mt-2 max-w-lg text-sm text-muted-foreground">Invite one person whose football knowledge complements yours—not a list of random contacts.</p><Button className="mt-5" onClick={share}><Share2Icon data-icon="inline-start" />Invite the first supporter</Button></div>}</section>
    <section className="mt-6 grid gap-5 border bg-foreground p-6 text-background lg:grid-cols-[1fr_auto] lg:items-center"><div><CrownIcon className="size-7 text-primary" /><h2 className="mt-3 font-heading text-3xl font-bold uppercase">Lead your founding community</h2><p className="mt-2 max-w-2xl text-background/70">A captain welcomes serious supporters and brings the weekly challenge back to the community. Each club has one founding captain.</p>{captainMessage ? <p className="mt-3 font-semibold text-primary" role="status">{captainMessage}</p> : null}</div>{identity.role === "captain" ? <Badge>Community captain</Badge> : identity.teamId ? <Button onClick={becomeCaptain} disabled={pending}>{pending ? <Spinner data-icon="inline-start" /> : <CrownIcon data-icon="inline-start" />}Become founding captain</Button> : <Button onClick={() => router.push("/onboarding")}>Choose your club first</Button>}</section>
  </div>;
}
