import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { CalendarDaysIcon, CheckIcon, CircleAlertIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { getMatchweekCalendar } from "@/data/member-planning";
import { getSession } from "@/lib/auth-session";

export const dynamic="force-dynamic"; export const metadata:Metadata={title:"Matchweek calendar"};
export default async function CalendarPage(){const session=await getSession();if(!session)redirect("/auth?next=/calendar");const weeks=await getMatchweekCalendar(session.user.id);const groups=Map.groupBy(weeks,(week)=>new Intl.DateTimeFormat("en",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(week.lockAt)));return <div className="page-shell py-10 sm:py-16"><header className="border-b pb-8"><CalendarDaysIcon className="size-7 text-primary"/><h1 className="mt-5 font-heading text-[clamp(3.5rem,7vw,6.5rem)] leading-[.88] font-extrabold uppercase">Matchweek calendar.</h1><p className="mt-4 max-w-2xl text-lg text-muted-foreground">Deadlines, fixtures, submitted locks, and missing actions across every league.</p></header><div className="mt-8 grid gap-10">{[...groups].map(([month,entries])=><section key={month} aria-labelledby={`month-${month.replaceAll(" ","-")}`}><h2 id={`month-${month.replaceAll(" ","-")}`} className="font-heading text-3xl font-bold uppercase">{month}</h2><div className="mt-3 divide-y border-y">{entries.map((week)=><article key={week.id} className="grid gap-4 px-4 py-5 md:grid-cols-[150px_1fr_auto] md:items-center"><time dateTime={week.lockAt} className="font-heading text-2xl">{new Intl.DateTimeFormat("en",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"UTC"}).format(new Date(week.lockAt))} UTC</time><div><Link href={`/leagues/${week.slug}`} className="font-bold hover:text-primary">{week.league} · {week.name}</Link><p className="mt-1 text-sm text-muted-foreground">{week.fixtures} fixtures · {week.status}</p></div><div className="flex flex-wrap gap-2">{week.ownPick?<Badge><CheckIcon data-icon="inline-start"/>Your lock</Badge>:week.followedPick?<Badge variant="outline"><CheckIcon data-icon="inline-start"/>Following</Badge>:<Badge variant="destructive"><CircleAlertIcon data-icon="inline-start"/>Action needed</Badge>}</div></article>)}</div></section>)}</div></div>}
