import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, CheckCircle2Icon, CheckIcon, ShieldIcon, UsersRoundIcon, XCircleIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import type { CommunityChallenge as ChallengeData, CommunityIdentity } from "@/data/distribution";
import { LocalTime } from "@/components/local-time";
import { chooseChallengeSide } from "@/app/challenges/actions";

function Side({ side, leading, selected, challengeId, signedIn }: { side: ChallengeData["home"]; leading: boolean; selected: boolean; challengeId: string; signedIn: boolean }) {
  const decisions = side.wins + side.losses;
  const accuracy = decisions ? Math.round(side.wins / decisions * 100) : 0;
  return <article className="flex flex-col items-center p-6 text-center sm:p-8">
    <div className="flex size-24 items-center justify-center">{side.logoUrl ? <Image src={side.logoUrl} alt="" width={96} height={96} className="size-24 object-contain" /> : <ShieldIcon className="size-16" />}</div>
    <h2 className="mt-4 font-heading text-4xl font-extrabold uppercase sm:text-5xl">{side.name}</h2>{leading ? <Badge className="mt-3">Currently leading</Badge> : null}
    <dl className="mt-6 grid w-full grid-cols-3 border-y py-4"><div><dt className="text-xs text-muted-foreground">Supporters</dt><dd className="font-heading text-3xl font-bold">{side.supporters}</dd></div><div><dt className="text-xs text-muted-foreground">Locks</dt><dd className="font-heading text-3xl font-bold">{side.locks}</dd></div><div><dt className="text-xs text-muted-foreground">Accuracy</dt><dd className="font-heading text-3xl font-bold">{decisions ? `${accuracy}%` : "—"}</dd></div></dl>
    {selected ? <Button className="mt-5 w-full" size="lg" disabled><CheckIcon data-icon="inline-start" />You represent {side.name}</Button> : signedIn ? <form action={chooseChallengeSide} className="mt-5 w-full"><input type="hidden" name="challengeId" value={challengeId} /><input type="hidden" name="teamId" value={side.id} /><Button type="submit" variant="outline" size="lg" className="w-full">Choose {side.name}</Button></form> : <Link href={`/auth?next=${encodeURIComponent(`/challenges/${challengeId}`)}`} className={buttonVariants({ variant: "outline", size: "lg", className: "mt-5 w-full" })}>Choose {side.name}</Link>}
  </article>;
}

export function CommunityChallenge({ data, identity }: { data: ChallengeData; identity: CommunityIdentity | null }) {
  const homeScore = data.home.wins - data.home.losses, awayScore = data.away.wins - data.away.losses;
  const represented = identity?.teamId === data.home.id ? data.home : identity?.teamId === data.away.id ? data.away : null;
  return <div>
    <header className="border-b bg-foreground text-background"><div className="page-shell grid gap-6 py-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="font-heading text-[clamp(3.5rem,8vw,7rem)] leading-[.85] font-extrabold uppercase">Community challenge</h1><p className="mt-4 text-background/70">Clubs. Supporters. One selective call at a time.</p></div><div className="border border-background/30 p-4"><span className="text-xs font-bold uppercase text-primary">Featured fixture</span><strong className="mt-1 block">{data.league.name}</strong><LocalTime value={data.kickoffAt} relative /></div></div></header>
    <main className="page-shell py-8 sm:py-12">
      <section className="grid border md:grid-cols-[1fr_auto_1fr]" aria-label={`${data.home.name} versus ${data.away.name}`}><Side side={data.home} leading={homeScore > awayScore} selected={identity?.teamId === data.home.id} challengeId={data.id} signedIn={identity !== null} /><div className="flex items-center justify-center border-y bg-muted px-5 py-3 font-heading text-3xl font-extrabold md:border-x md:border-y-0">VS</div><Side side={data.away} leading={awayScore > homeScore} selected={identity?.teamId === data.away.id} challengeId={data.id} signedIn={identity !== null} /></section>
      <section className="mt-6 grid border sm:grid-cols-3"><div className="border-b p-5 sm:border-r sm:border-b-0"><UsersRoundIcon className="size-6 text-primary" /><strong className="mt-2 block font-heading text-4xl">{data.home.supporters + data.away.supporters}</strong><span className="text-sm text-muted-foreground">Representing supporters</span></div><div className="border-b p-5 sm:border-r sm:border-b-0"><ShieldIcon className="size-6 text-primary" /><strong className="mt-2 block font-heading text-4xl">{data.home.locks + data.away.locks}</strong><span className="text-sm text-muted-foreground">Permanent calls</span></div><div className="p-5"><strong className="block font-heading text-4xl text-primary">{represented ? represented.name : "Choose a side"}</strong><span className="text-sm text-muted-foreground">{represented ? "You represent this club" : "Set your club identity to participate"}</span></div></section>
      <section className="mt-6 border" aria-labelledby="challenge-calls"><div className="flex items-end justify-between gap-4 border-b p-5"><div><h2 id="challenge-calls" className="font-heading text-3xl font-bold uppercase">Recent settled calls</h2><p className="mt-1 text-sm text-muted-foreground">Wins and misses stay visible. Pending locks remain private.</p></div><Link href={`/leagues/${data.league.slug}`} className="text-sm font-semibold underline">Open league</Link></div>{data.recentCalls.length ? <div className="divide-y">{data.recentCalls.map((call) => <article key={call.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><strong>{call.supporter}</strong><p className="text-xs text-muted-foreground">{call.reason ?? "No public reason supplied"}</p></div><span className="font-semibold">{call.team}</span><Badge variant={call.result === "win" ? "default" : "destructive"}>{call.result === "win" ? <CheckCircle2Icon data-icon="inline-start" /> : <XCircleIcon data-icon="inline-start" />}{call.result}</Badge></article>)}</div> : <div className="p-8 text-center"><h3 className="font-heading text-3xl font-bold uppercase">The challenge starts with the first call</h3><p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground">No settled community calls yet. Represent your club and make one selective Daily Lock in the league you know.</p></div>}</section>
      <section className="mt-6 grid gap-5 border bg-foreground p-6 text-background sm:grid-cols-[1fr_auto] sm:items-center"><div><h2 className="font-heading text-4xl font-bold uppercase">Represent your club.</h2><p className="mt-2 text-background/70">Every honest call strengthens the public record of the community behind it.</p></div><Link href={identity ? represented ? `/leagues/${data.league.slug}` : "/onboarding" : `/auth?next=${encodeURIComponent(`/challenges/${data.id}`)}`} className={buttonVariants({ size: "lg" })}>{represented ? "Make your Daily Lock" : identity ? "Choose your club" : "Create an account"}<ArrowRightIcon data-icon="inline-end" /></Link></section>
    </main>
  </div>;
}
