import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, CheckCircle2Icon, CrownIcon, ShieldIcon, UsersRoundIcon, XCircleIcon } from "lucide-react";

import { ChallengeShareCard, KickoffCountdown, MobileChallengeBar, SideChoice } from "@/components/challenges/challenge-interactions";
import { LocalTime } from "@/components/local-time";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import type { CommunityChallenge as ChallengeData, CommunityIdentity } from "@/data/distribution";

function Side({ side, leading, selected, challengeId, signedIn }: { side: ChallengeData["home"]; leading: boolean; selected: boolean; challengeId: string; signedIn: boolean }) {
  const decisions = side.wins + side.losses;
  const accuracy = decisions ? Math.round(side.wins / decisions * 100) : 0;
  return <article className="flex flex-col items-center p-6 text-center sm:p-8">
    <div className="flex size-24 items-center justify-center">{side.logoUrl ? <Image src={side.logoUrl} alt="" width={96} height={96} className="size-24 object-contain" /> : <ShieldIcon className="size-16" />}</div>
    <h2 className="mt-4 font-heading text-4xl font-extrabold uppercase sm:text-5xl">{side.name}</h2>
    {leading ? <Badge className="mt-3">Currently leading</Badge> : null}
    <dl className="mt-6 grid w-full grid-cols-3 border-y py-4"><div><dt className="text-xs text-muted-foreground">Supporters</dt><dd className="font-heading text-3xl font-bold">{side.supporters}</dd></div><div><dt className="text-xs text-muted-foreground">Locks</dt><dd className="font-heading text-3xl font-bold">{side.locks}</dd></div><div><dt className="text-xs text-muted-foreground">Accuracy</dt><dd className="font-heading text-3xl font-bold">{decisions ? `${accuracy}%` : "—"}</dd></div></dl>
    {side.supporters === 0 ? <p className="mt-4 text-sm font-semibold text-primary">Be the first {side.name} supporter to stand here.</p> : null}
    <SideChoice challengeId={challengeId} side={side} signedIn={signedIn} selected={selected} className="mt-5" />
  </article>;
}

function ComparisonMetric({ label, home, away, homeName, awayName }: { label: string; home: number; away: number; homeName: string; awayName: string }) {
  const total = home + away;
  const homeWidth = total ? Math.round(home / total * 100) : 50;
  return <div><div className="flex items-center justify-between gap-4 text-sm"><span><strong>{home}</strong> {homeName}</span><span className="text-xs font-bold uppercase text-muted-foreground">{label}</span><span>{awayName} <strong>{away}</strong></span></div><div className="mt-2 grid h-3 overflow-hidden bg-muted" style={{ gridTemplateColumns: `${homeWidth}% ${100 - homeWidth}%` }} aria-label={`${label}: ${homeName} ${home}, ${awayName} ${away}`}><span className="bg-primary" /><span className="bg-inverted" /></div></div>;
}

function Leaderboard({ side }: { side: ChallengeData["home"] }) {
  return <article className="border"><header className="flex items-center gap-3 border-b p-5"><CrownIcon className="size-6 text-primary" /><div><h3 className="font-heading text-2xl font-bold uppercase">{side.name} leaders</h3><p className="text-xs text-muted-foreground">Settled independent calls</p></div></header>{side.leaders.length ? <ol className="divide-y">{side.leaders.map((leader, index) => <li key={leader.id} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 p-4"><span className="flex size-8 items-center justify-center border font-heading font-bold">{index + 1}</span><div><Link href={`/specialists/${leader.handle ?? leader.id}`} className="font-bold hover:text-primary">{leader.name}</Link><p className="text-xs text-muted-foreground">{leader.wins}–{leader.losses} across {leader.locks} calls</p></div><strong className="font-heading text-2xl text-primary">{leader.accuracy}%</strong></li>)}</ol> : <div className="p-7 text-center"><strong className="font-heading text-2xl uppercase">First place is open</strong><p className="mt-2 text-sm text-muted-foreground">The first settled {side.name} call starts this board.</p></div>}</article>;
}

export function CommunityChallenge({ data, identity }: { data: ChallengeData; identity: CommunityIdentity | null }) {
  const homeScore = data.home.wins - data.home.losses;
  const awayScore = data.away.wins - data.away.losses;
  const represented = identity?.teamId === data.home.id ? data.home : identity?.teamId === data.away.id ? data.away : null;
  return <div>
    <header className="border-b bg-inverted text-inverted-foreground"><div className="page-shell grid gap-6 py-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="font-heading text-[clamp(3.5rem,8vw,7rem)] leading-[.85] font-extrabold uppercase">Community challenge</h1><p className="mt-4 text-inverted-foreground/70">Clubs. Supporters. One selective call at a time.</p></div><div className="border border-inverted-foreground/30 p-4"><span className="text-xs font-bold uppercase text-primary">Featured fixture</span><strong className="mt-1 block">{data.league.name}</strong><LocalTime value={data.kickoffAt} relative /><KickoffCountdown kickoffAt={data.kickoffAt} /></div></div></header>
    <main className="page-shell py-8 pb-32 sm:py-12 md:pb-12">
      <section className="grid border md:grid-cols-[1fr_auto_1fr]" aria-label={`${data.home.name} versus ${data.away.name}`}><Side side={data.home} leading={homeScore > awayScore} selected={identity?.teamId === data.home.id} challengeId={data.id} signedIn={identity !== null} /><div className="flex items-center justify-center border-y bg-muted px-5 py-3 font-heading text-3xl font-extrabold md:border-x md:border-y-0">VS</div><Side side={data.away} leading={awayScore > homeScore} selected={identity?.teamId === data.away.id} challengeId={data.id} signedIn={identity !== null} /></section>
      <section className="mt-6 border p-5 sm:p-6" aria-labelledby="challenge-progress"><div className="mb-5"><h2 id="challenge-progress" className="font-heading text-3xl font-bold uppercase">Challenge momentum</h2><p className="text-sm text-muted-foreground">The balance shifts as real supporters join and permanent calls settle.</p></div><div className="grid gap-5"><ComparisonMetric label="Supporters" home={data.home.supporters} away={data.away.supporters} homeName={data.home.name} awayName={data.away.name} /><ComparisonMetric label="Permanent calls" home={data.home.locks} away={data.away.locks} homeName={data.home.name} awayName={data.away.name} /><ComparisonMetric label="Net correct" home={Math.max(0, homeScore)} away={Math.max(0, awayScore)} homeName={data.home.name} awayName={data.away.name} /></div></section>
      <section className="mt-6 grid border sm:grid-cols-3"><div className="border-b p-5 sm:border-r sm:border-b-0"><UsersRoundIcon className="size-6 text-primary" /><strong className="mt-2 block font-heading text-4xl">{data.home.supporters + data.away.supporters}</strong><span className="text-sm text-muted-foreground">Representing supporters</span></div><div className="border-b p-5 sm:border-r sm:border-b-0"><ShieldIcon className="size-6 text-primary" /><strong className="mt-2 block font-heading text-4xl">{data.home.locks + data.away.locks}</strong><span className="text-sm text-muted-foreground">Permanent calls</span></div><div className="p-5"><strong className="block font-heading text-4xl text-primary">{represented ? represented.name : "Choose a side"}</strong><span className="text-sm text-muted-foreground">{represented ? "You represent this club" : "Your club identity powers the challenge"}</span></div></section>
      <section className="mt-6" aria-labelledby="side-leaders"><div className="mb-4"><h2 id="side-leaders" className="font-heading text-3xl font-bold uppercase">Supporters setting the standard</h2><p className="text-sm text-muted-foreground">Accuracy is always shown with its sample size.</p></div><div className="grid gap-5 lg:grid-cols-2"><Leaderboard side={data.home} /><Leaderboard side={data.away} /></div></section>
      <section className="mt-6 border" aria-labelledby="challenge-calls"><div className="flex items-end justify-between gap-4 border-b p-5"><div><h2 id="challenge-calls" className="font-heading text-3xl font-bold uppercase">Recent settled calls</h2><p className="mt-1 text-sm text-muted-foreground">Wins and misses stay visible. Pending locks remain private.</p></div><Link href={`/leagues/${data.league.slug}`} className="text-sm font-semibold underline">Open league</Link></div>{data.recentCalls.length ? <div className="divide-y">{data.recentCalls.map((call) => <article key={call.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><strong>{call.supporter}</strong><p className="text-xs text-muted-foreground">{call.reason ?? "No public reason supplied"}</p></div><span className="font-semibold">{call.team}</span><Badge variant={call.result === "win" ? "default" : "destructive"}>{call.result === "win" ? <CheckCircle2Icon data-icon="inline-start" /> : <XCircleIcon data-icon="inline-start" />}{call.result}</Badge></article>)}</div> : <div className="grid gap-5 p-8 text-center sm:grid-cols-2 sm:text-left"><div><h3 className="font-heading text-3xl font-bold uppercase">The first call writes the story</h3><p className="mt-2 text-sm text-muted-foreground">No settled community calls yet. There is nothing to fake and nothing hidden.</p></div><div className="border-l-4 border-primary pl-5"><strong className="block">A leaderboard with no shortcuts.</strong><p className="mt-2 text-sm text-muted-foreground">Represent your club, make one selective Daily Lock, and return after settlement.</p></div></div>}</section>
      <ChallengeShareCard challengeId={data.id} homeName={data.home.name} awayName={data.away.name} representedName={represented?.name ?? null} representedSlug={represented?.slug ?? null} />
      <section className="mt-6 grid gap-5 border bg-inverted p-6 text-inverted-foreground sm:grid-cols-[1fr_auto] sm:items-center"><div><h2 className="font-heading text-4xl font-bold uppercase">{represented ? `Build the ${represented.name} side.` : "Represent your club."}</h2><p className="mt-2 text-inverted-foreground/70">{represented ? "Invite supporters who genuinely understand the club, then make your strongest call." : "Every honest call strengthens the public record of the community behind it."}</p></div><Link href={represented ? "/invite" : identity ? "/onboarding" : `/auth?next=${encodeURIComponent(`/challenges/${data.id}`)}`} className={buttonVariants({ size: "lg" })}>{represented ? "Invite supporters" : identity ? "Choose your club" : "Create an account"}<ArrowRightIcon data-icon="inline-end" /></Link></section>
    </main>
    <MobileChallengeBar challengeId={data.id} home={data.home} away={data.away} signedIn={identity !== null} represented={represented ? { name: represented.name, slug: represented.slug } : null} />
  </div>;
}
